# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# IP: ip/coffee_rom/coffee_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==coffee_rom || ORIG_REF_NAME==coffee_rom} -quiet] -quiet

# Block Designs: bd/mb_usb/mb_usb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb || ORIG_REF_NAME==mb_usb} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_1/mb_usb_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_1 || ORIG_REF_NAME==mb_usb_microblaze_0_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_v10_1/mb_usb_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_v10_1 || ORIG_REF_NAME==mb_usb_dlmb_v10_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_v10_1/mb_usb_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_v10_1 || ORIG_REF_NAME==mb_usb_ilmb_v10_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_1/mb_usb_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_usb_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_1/mb_usb_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mb_usb_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_lmb_bram_1/mb_usb_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_lmb_bram_1 || ORIG_REF_NAME==mb_usb_lmb_bram_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_xbar_1/mb_usb_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_xbar_1 || ORIG_REF_NAME==mb_usb_xbar_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_periph_1/mb_usb_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_periph_1 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_1/mb_usb_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_intc_1 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_xlconcat_1/mb_usb_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_xlconcat_1 || ORIG_REF_NAME==mb_usb_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_mdm_1_1/mb_usb_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_mdm_1_1 || ORIG_REF_NAME==mb_usb_mdm_1_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_clk_wiz_1_1/mb_usb_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_clk_wiz_1_1 || ORIG_REF_NAME==mb_usb_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_1/mb_usb_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_usb_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_3/mb_usb_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_3 || ORIG_REF_NAME==mb_usb_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_4/mb_usb_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_4 || ORIG_REF_NAME==mb_usb_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_gpio_0_5/mb_usb_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_gpio_0_5 || ORIG_REF_NAME==mb_usb_axi_gpio_0_5} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_uartlite_0_1/mb_usb_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_uartlite_0_1 || ORIG_REF_NAME==mb_usb_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_timer_0_1/mb_usb_axi_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_timer_0_1 || ORIG_REF_NAME==mb_usb_axi_timer_0_1} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_quad_spi_0_1/mb_usb_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_usb_axi_quad_spi_0_1} -quiet] -quiet

# XDC: c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc
