# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.runs/synth_1/mb_usb_hdmi_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.cache/wt [current_project]
set_property parent.project_path C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{c:/Users/Jnzhu/Downloads/College and SAT/ECE 385/RD_hdmi_ip2020}} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/waterfall/waterfall.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/among_us_map/among_us_map.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/sprite_0/sprite_0.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/sprite_1/sprite_1.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/sprite_2/sprite_2.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/left_character0/left_character0.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/left_character1/left_character1.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/left_character2/left_character2.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/boundaries0/boundaries0.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/boundaries/boundaries.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/eceb_map/eceb_map.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/printer/printer.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/printer_fail/printer_fail.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/printer_success/printer_success.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/start_screen/start_screen.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/coffee/coffee.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/coffee_pour/coffee_pour.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/coffee_successful/coffee_successful.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/coffee_fail/coffee_fail.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/coffee_overflow/coffee_overflow.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/fail/fail.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/win/win.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/lab_report/lab_report.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/vials/vials.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/vials_sprite/vials_sprite.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/shower_on/shower_on.COE
add_files C:/Users/Jnzhu/Documents/GitHub/Image_to_COE/maze/maze.COE
read_verilog -library xil_defaultlib -sv {
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/new/Animate.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/design_source/Color_Mapper.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/design_source/VGA_controller.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/design_source/ball.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/new/big_fsm.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/new/coffee_color_mapper.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/coffee_fail/coffee_fail_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/coffee_overflow/coffee_overflow_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/coffee/coffee_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/coffee_successful/coffee_successful_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/eceb_map/eceb_map_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/eceb_map/eceb_map_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/new/eceb_walls.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/fail/fail_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/design_source/hex_driver.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/left_character0/left_character0_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/left_character0/left_character0_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/left_character1/left_character1_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/left_character1/left_character1_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/left_character2/left_character2_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/left_character2/left_character2_palette.sv
  {C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/ECE 385/num_color_mapper.sv}
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/printer/printer_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/sprite_0/sprite_0_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/sprite_0/sprite_0_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/sprite_1/sprite_1_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/sprite_1/sprite_1_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/sprite_2/sprite_2_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/sprite_2/sprite_2_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/start_screen/start_screen_example.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/start_screen/start_screen_palette.sv
  {C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/ECE 385/task_coffee.sv}
  {C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/ECE 385/task_num.sv}
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Downloads/task_vials.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Downloads/vials_color_mapper.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/vials/vials_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/Image_to_COE/vials_sprite/vials_sprite_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/win/win_palette.sv
  C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/imports/design_source/mb_usb_hdmi_top.sv
}
read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/coffee_rom/coffee_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/coffee_rom/coffee_rom_ooc.xdc]

add_files C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/bd/mb_usb/mb_usb.bd
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_1/mb_usb_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_1/mb_usb_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_1/mb_usb_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_v10_1/mb_usb_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_v10_1/mb_usb_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_1/mb_usb_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_1/mb_usb_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_1/mb_usb_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_1/mb_usb_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_1/mb_usb_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_1/mb_usb_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_1/mb_usb_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_mdm_1_1/mb_usb_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_mdm_1_1/mb_usb_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_1/mb_usb_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_1/mb_usb_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_clk_wiz_1_1/mb_usb_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_1/mb_usb_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_1/mb_usb_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_1/mb_usb_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_3/mb_usb_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_3/mb_usb_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_3/mb_usb_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_4/mb_usb_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_4/mb_usb_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_4/mb_usb_axi_gpio_0_4.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_5/mb_usb_axi_gpio_0_5_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_5/mb_usb_axi_gpio_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_gpio_0_5/mb_usb_axi_gpio_0_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_1/mb_usb_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_1/mb_usb_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_uartlite_0_1/mb_usb_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_timer_0_1/mb_usb_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_timer_0_1/mb_usb_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_quad_spi_0_1/mb_usb_axi_quad_spi_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_quad_spi_0_1/mb_usb_axi_quad_spi_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_quad_spi_0_1/mb_usb_axi_quad_spi_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_axi_quad_spi_0_1/mb_usb_axi_quad_spi_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/bd/mb_usb/ip/mb_usb_microblaze_0_1/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/sprite_0_rom/sprite_0_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/sprite_0_rom/sprite_0_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/sprite_1_rom/sprite_1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/sprite_1_rom/sprite_1_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/sprite_2_rom/sprite_2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/sprite_2_rom/sprite_2_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/left_character0_rom/left_character0_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/left_character0_rom/left_character0_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/left_character1_rom/left_character1_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/left_character1_rom/left_character1_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/left_character2_rom/left_character2_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/left_character2_rom/left_character2_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/eceb_map_rom/eceb_map_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/eceb_map_rom/eceb_map_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/task_num_rom/task_num_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/task_num_rom/task_num_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/start_screen_rom/start_screen_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/start_screen_rom/start_screen_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/coffee_successful_rom/coffee_successful_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/coffee_successful_rom/coffee_successful_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/coffee_fail_rom/coffee_fail_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/coffee_fail_rom/coffee_fail_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/coffee_overflow_rom/coffee_overflow_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/coffee_overflow_rom/coffee_overflow_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/task_num_fail_rom_1/task_num_fail_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/task_num_fail_rom_1/task_num_fail_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/task_num_win_rom_1/task_num_win_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/task_num_win_rom_1/task_num_win_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/vials_rom/vials_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/vials_rom/vials_rom_ooc.xdc]

read_ip -quiet C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/sources_1/ip/task_vials_sprite_rom/task_vials_sprite_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.gen/sources_1/ip/task_vials_sprite_rom/task_vials_sprite_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc
set_property used_in_implementation false [get_files C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/constrs_1/imports/pin_assignment/mb_usb_hdmi_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/Jnzhu/Documents/Vivado/Among_Us/Among_Us.srcs/utils_1/imports/synth_1/mb_usb_hdmi_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mb_usb_hdmi_top -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mb_usb_hdmi_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mb_usb_hdmi_top_utilization_synth.rpt -pb mb_usb_hdmi_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
